<template>
    <section id="marketplace" class="w-full">
        <section id="backdrop" class="backdrop bg-gray-100 absolute top-0 left-0 w-full full-height hidden opacity-0"></section>
        <header class="w-full mx-auto screen xl:py-12 py-4">
            <h4 class="text-center 2xl:text-xl lg:text-lg text-md text-gray-700">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime vitae vel assumenda! <br />
                Lorem ipsum dolor sit.
            </h4>
        </header>
        <nav class="2xl:w-6/12 md:w-4/12 mx-auto">
            <ul id="carousel" class="w-full" >
                <li :id="`book-${index}-carousel-item`" :key="`thumb-book-${index}`" v-for="(book, index) in books" class="md:w-4/12">
                    <div class="w-full px-1">
                        <component :is="`thumb-${book}`"></component>
                    </div>
                </li>
            </ul>
            <section :class="{'hidden': books.lemgth}" class="w-full text-center">
                <button id="book-prev" class="text-xl mx-4 text-orange-400 focus:text-orange-500 focus:outline-none">
                    <i class="fa fa-arrow-left"></i>
                </button>
                <button id="book-next" class="text-xl mx-4 text-orange-400 focus:text-orange-500 focus:outline-none">
                    <i class="fa fa-arrow-right"></i>
                </button>
            </section>
        </nav>
        <component :key="`book-${index}`" v-for="(book, index) in books" :is="book"></component>
    </section>
</template>
<script>
import books from "../assets/js/book.list";

export default {
    name: "Marketplace",
    data() {
        return {
            books
        }
    },
    methods: {
        initSlick() {
            window.$('#carousel').slick({
                infinite: false,
                centerMode: false,
                centerPadding: '20px',
                slidesToShow: 1,
                slidesToScroll: 1,
                swipe: false,
                prevArrow: window.$('#book-prev'),
                nextArrow: window.$('#book-next')
            });            
        }
    },
    created() {
        console.log('(づ￣ ³￣)づ');
        this.books.forEach((book) => {
            this.$options.components[`thumb-${book}`] = () => import(`./thumbs/thumb_${book}.vue`);
            this.$options.components[book] = () => import(`./books/${book}.vue`);
        });
    },
    mounted() {
        this.initSlick();
    }
}
</script>
<style lang="stylus">
    .backdrop
        z-index 999
        transition opacity ease 200ms
</style>
<style scoped>
.vibrate-1 {
	-webkit-animation: vibrate-1 0.3s linear both;
	        animation: vibrate-1 0.3s linear both;
}
/* ----------------------------------------------
 * Generated by Animista on 2021-4-8 16:55:5
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation vibrate-1
 * ----------------------------------------
 */
@-webkit-keyframes vibrate-1 {
  0% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
  20% {
    -webkit-transform: translate(-2px, 2px);
            transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(-2px, -2px);
            transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, 2px);
            transform: translate(2px, 2px);
  }
  80% {
    -webkit-transform: translate(2px, -2px);
            transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
}
@keyframes vibrate-1 {
  0% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
  20% {
    -webkit-transform: translate(-2px, 2px);
            transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(-2px, -2px);
            transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, 2px);
            transform: translate(2px, 2px);
  }
  80% {
    -webkit-transform: translate(2px, -2px);
            transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
}

</style>